#############################################################################
# Makefile for building: candy.app/Contents/MacOS/candy
# Generated by qmake (2.01a) (Qt 4.8.1) on: Fri Aug 28 17:48:20 2015
# Project:  candy.pro
# Template: app
# Command: /Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/bin/qmake -spec /Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/macx-g++ CONFIG+=declarative_debug -o Makefile candy.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
INCPATH       = -I/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/macx-g++ -I. -I/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtCore.framework/Versions/4/Headers -I/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/include/QtCore -I/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtGui.framework/Versions/4/Headers -I/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/include/QtGui -I/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/include -I. -I. -F/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/lib
LINK          = g++
LFLAGS        = -headerpad_max_install_names -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5
LIBS          = $(SUBLIBS) -F/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/lib -L/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/lib -framework QtGui -L/usr/local/pgsql/lib -L/tmp/qt-stuff-85167/source/qt-everywhere-opensource-src-4.8.1/Desktop/Qt/4.8.1/gcc/lib -F/tmp/qt-stuff-85167/source/qt-everywhere-opensource-src-4.8.1/Desktop/Qt/4.8.1/gcc/lib -framework QtCore 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = candydialog.cpp \
		main.cpp moc_candydialog.cpp \
		qrc_candy.cpp
OBJECTS       = candydialog.o \
		main.o \
		moc_candydialog.o \
		qrc_candy.o
DIST          = /Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/unix.conf \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/mac.conf \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base.conf \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base-macx.conf \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-base.conf \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-macx.conf \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/qconfig.pri \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/modules/qt_webkit_version.pri \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_functions.prf \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_config.prf \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/exclusive_builds.prf \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_pre.prf \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/default_pre.prf \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/dwarf2.prf \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/debug.prf \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_post.prf \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/default_post.prf \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/x86_64.prf \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/objective_c.prf \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/declarative_debug.prf \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/warn_on.prf \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt.prf \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/thread.prf \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/moc.prf \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/rez.prf \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/sdk.prf \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/resources.prf \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/uic.prf \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/yacc.prf \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/lex.prf \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/include_source_dir.prf \
		candy.pro
QMAKE_TARGET  = candy
DESTDIR       = 
TARGET        = candy.app/Contents/MacOS/candy

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-arch \
		x86_64 \
		-Xarch_x86_64 \
		-mmacosx-version-min=10.5 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile candy.app/Contents/PkgInfo candy.app/Contents/Resources/empty.lproj candy.app/Contents/Info.plist $(TARGET)

$(TARGET): ui_candy.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) candy.app/Contents/MacOS/ || $(MKDIR) candy.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: candy.pro  /Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/macx-g++/qmake.conf /Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/unix.conf \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/mac.conf \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base.conf \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base-macx.conf \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-base.conf \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-macx.conf \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/qconfig.pri \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/modules/qt_webkit_version.pri \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_functions.prf \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_config.prf \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/exclusive_builds.prf \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_pre.prf \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/default_pre.prf \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/dwarf2.prf \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/debug.prf \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_post.prf \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/default_post.prf \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/x86_64.prf \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/objective_c.prf \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/declarative_debug.prf \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/warn_on.prf \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt.prf \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/thread.prf \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/moc.prf \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/rez.prf \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/sdk.prf \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/resources.prf \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/uic.prf \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/yacc.prf \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/lex.prf \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/include_source_dir.prf \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtGui.framework/QtGui.prl \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec /Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/macx-g++ CONFIG+=declarative_debug -o Makefile candy.pro
/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/unix.conf:
/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/mac.conf:
/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base.conf:
/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base-macx.conf:
/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-base.conf:
/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-macx.conf:
/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/qconfig.pri:
/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/modules/qt_webkit_version.pri:
/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_functions.prf:
/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_config.prf:
/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/exclusive_builds.prf:
/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_pre.prf:
/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/default_pre.prf:
/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/dwarf2.prf:
/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/debug.prf:
/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_post.prf:
/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/default_post.prf:
/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/x86_64.prf:
/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/objective_c.prf:
/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/declarative_debug.prf:
/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/warn_on.prf:
/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt.prf:
/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/thread.prf:
/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/moc.prf:
/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/rez.prf:
/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/sdk.prf:
/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/resources.prf:
/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/uic.prf:
/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/yacc.prf:
/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/lex.prf:
/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/include_source_dir.prf:
/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtGui.framework/QtGui.prl:
/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtCore.framework/QtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/macx-g++ CONFIG+=declarative_debug -o Makefile candy.pro

candy.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) candy.app/Contents || $(MKDIR) candy.app/Contents 
	@$(DEL_FILE) candy.app/Contents/PkgInfo
	@echo "APPL????" >candy.app/Contents/PkgInfo
candy.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) candy.app/Contents/Resources || $(MKDIR) candy.app/Contents/Resources 
	@touch candy.app/Contents/Resources/empty.lproj
	
candy.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) candy.app/Contents || $(MKDIR) candy.app/Contents 
	@$(DEL_FILE) candy.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,candy,g" -e "s,@TYPEINFO@,????,g" /Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/macx-g++/Info.plist.app >candy.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/candy1.0.0 || $(MKDIR) .tmp/candy1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/candy1.0.0/ && $(COPY_FILE) --parents candydialog.h .tmp/candy1.0.0/ && $(COPY_FILE) --parents candy.qrc .tmp/candy1.0.0/ && $(COPY_FILE) --parents candydialog.cpp main.cpp .tmp/candy1.0.0/ && $(COPY_FILE) --parents candy.ui .tmp/candy1.0.0/ && (cd `dirname .tmp/candy1.0.0` && $(TAR) candy1.0.0.tar candy1.0.0 && $(COMPRESS) candy1.0.0.tar) && $(MOVE) `dirname .tmp/candy1.0.0`/candy1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/candy1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r candy.app
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_candydialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_candydialog.cpp
moc_candydialog.cpp: candydialog.h
	/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ candydialog.h -o moc_candydialog.cpp

compiler_rcc_make_all: qrc_candy.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_candy.cpp
qrc_candy.cpp: candy.qrc \
		BECWords.txt \
		qss/candy.qss \
		images/button-start.png \
		images/button-hover.png \
		images/down-arrow.png \
		images/button.png \
		images/wrong.png \
		images/heart.png \
		images/button-pressed.png \
		images/right.png \
		images/background.png
	/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/bin/rcc -name candy candy.qrc -o qrc_candy.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all: ui_candy.h
compiler_uic_clean:
	-$(DEL_FILE) ui_candy.h
ui_candy.h: candy.ui
	/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/bin/uic candy.ui -o ui_candy.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

candydialog.o: candydialog.cpp candydialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o candydialog.o candydialog.cpp

main.o: main.cpp candydialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

moc_candydialog.o: moc_candydialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_candydialog.o moc_candydialog.cpp

qrc_candy.o: qrc_candy.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_candy.o qrc_candy.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

